import { renderPolicyPage } from "../helpers/_policyPage.js";

/**
 * AI Usage Policy template (v1).
 *
 * AUTHORING CONTRACT:
 * - NO frontmatter here
 * - NO layout logic here
 * - NO imports from @legal
 * - NO filesystem access
 * - Body HTML ONLY
 *
 * AVAILABLE VARIABLES (in body HTML):
 * - organisation.name
 * - organisation.jurisdiction
 * - organisation.address
 * - organisation.companyNumber
 * - contacts.privacyEmail
 * - contacts.legalEmail
 * - contacts.abuseEmail
 * - contacts.lawEnforcementEmail
 * - contacts.securityEmail
 *
 * SOURCE:
 * - All variables are injected by renderPolicyPage()
 * - This file MUST NOT redefine or extend them
 *
 * VERSIONING:
 * - This contract is stable for v1
 * - Adding new variables requires v2
 */
export function renderAiUsagePolicy(): string {
  return renderPolicyPage({
    title: "AI Usage Policy",

    body: `
<h2>1. Purpose and scope</h2>

<p>
This policy explains expectations for AI-related use of the Services
operated by <strong>{organisation.name}</strong>. It applies to any use
of AI or machine learning features, models, or outputs accessed through
the Services.
</p>

<h2>2. Definitions</h2>

<p>
"AI systems" include machine learning models, automated decision
systems, or generative tools. "Outputs" refer to content generated by
AI systems, including text, images, audio, or code.
</p>

<h2>3. Policy statement</h2>

<p>
AI features should be used responsibly, lawfully, and with appropriate
oversight. You remain responsible for how outputs are used, shared, and
distributed.
</p>

<h2>4. Acceptable use</h2>

<ul>
  <li>Use AI features for lawful and ethical purposes</li>
  <li>Review outputs before use or publication</li>
  <li>Respect privacy and intellectual property rights</li>
</ul>

<h2>5. Prohibited use</h2>

<ul>
  <li>Generating or distributing unlawful or harmful content</li>
  <li>Impersonation, deception, or fraud</li>
  <li>Automated harassment or targeted abuse</li>
  <li>Attempting to bypass safety safeguards</li>
</ul>

<h2>6. Transparency and accountability</h2>

<p>
Where appropriate, you should disclose AI-generated content and ensure
users are not misled about the origin of materials.
</p>

<h2>7. Reporting and contact</h2>

<p>
AI usage concerns can be reported to:
<strong>{contacts.abuseEmail}</strong> or
<strong>{contacts.legalEmail}</strong>.
</p>

<h2>8. Policy updates</h2>

<p>
Material changes will update the effective date above.
</p>
`
  });
}
